# Minecraft Server Verwaltungs Werkzeug
# Version de 2.5.20 erstellt von CrazyCloudCraft 15.05.2022 https://crazycloudcraft.de/

# Verwende STRG + k + x um die Einstellungen zu speichern (mithilfe des joe's Bearbeitungsprogramm)
# Verwende STRG + c um alle Einstellungen abzubrechen (Du kannst die Einstellungen mit ./config öffnen)

# Wähle deine Minecraft Version 1.18.2, 1.18.1, 1.18, ...
# Manche Software typen brauchen keine Minecraft Version z.B. Velocity oder Bungeecord. 
# Aber man sollte sie trotzdem hier eintragen.
version: 1.18.2

# Was für eine Software willst du eigentlich verwenden?
# Du kannst hier < PAPER | PURPUR | MOHIST | VELOCITY | BUNGEECORD | SPIGOT | BUKKIT > hinschreiben.
software: PAPER

# Welche(r) Unterordner verwendest du für deine Server? Du musst einen verwenden.
# z.B. home/server/(...) oder opt/(...)
servers.directory: opt

# Wie heißt der Hauptordner wo der Server läuft?
main.directory: Paper

# Welchen System-Namen soll die Konsole und die main.jar haben?
# Nutze keine Namen wie zum Beispiel "system" oder "main", 
# weil diese eventuell schon vom System belegt sind.
systemname: mcpaper
# Sicherer ist, wenn du "mc" vor dem Namen schreibst ;)

# Wie viel Ram soll dein Server bekommen? 
# Der Server nutzt M und G ohne dem B dahinter. z.B.: RAM=2024M oder RAM=10G
ram: 4GB

# Wo befinndet sich das Java?
# (Default java) was man mit "java --version" erreicht, ist z.B.: JAVABIN=/usr/bin/java
java: /usr/bin/java
# Dieses feature wird bald durch ein automatisches system ersetzt!

# Soll oder ist dieser Server mit einem Proxy (Bungeecord/Waterfall etc.) verbunden? 
proxy.mode: false

# --- Backups ---
# Brauchst du Backups? 
# Dann musst du das hier auf "true" setzen.
backups: false

# Möchtest du bessere backups? (Es reduziert die Dateiengröße sehr, und behält nur alle nötigen dinge)
primebackups: false

# --- Bedrock Edition (MCPE) ---
# Willst du, dass Bedrock Edition Spieler auch mitspielen können?
bedrock: false

# --- Bearbeitsfähige Nachrichten ---
# Du auch hier auch Minecraft farben hinzufuegen:

MPREFIX="§8[§aArgantiu§8]"

# Farbliste:

# Black:        \033[0;30m'     Dark Gray:     \033[1;30m'
# Red:          \033[0;31m'     Light Red:     \033[1;31m'
# Green:        \033[0;32m'     Light Green:   \033[1;32m'
# Brown/Orange: \033[0;33m'     Yellow:        \033[1;33m'
# Blue:         \033[0;34m'     Light Blue:    \033[1;34m'
# Purple:       \033[0;35m'     Light Purple:  \033[1;35m'
# Cyan:         \033[0;36m'     Light Cyan:    \033[1;36m'
# Light Gray:   \033[0;37m'     White:         \033[1;37m'
#MTPATH=/$OPTBASE/$SERVERBASE
# Konfiguration zu ende. Wenn das nicht hier stehen würde, dann ist die Datei kaputt!
